🐳 Container automations for sync

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -12,7 +12,20 @@ services:
           echo "🛑 \`npm start\` failed, but the container is running..." && \
           tail -f /dev/null \
         )
-
     ports:
       - 3000:3000
-        
+
+  sync:
+    image: node
+    volumes:
+      - "./sync:/mnt/sync"
+    working_dir: "/mnt/sync"
+    entrypoint: "/bin/bash -c"
+    command:
+      - |
+        CI=true npm start || (\
+          echo "🛑 \`npm start\` failed, but the container is running..." && \
+          tail -f /dev/null \
+        )
+    ports:
+      - 4000:4000
